### PR TITLE
Allow images to be shown inline for tumble.

### PR DESCRIPTION
**Pull request by stahnma**
There are 3 commits here. 
1. Fix up CRLF because WTF.
2. Change shebangs to /usr/bin 100% of the places, since it wasn't consistent.
3. The real commit.

Allow images to be shown inline for tumble.

Prior to this commit any link added to tumble via the web api (as used by chat bots) would be simple text displayed on tumble. This seemed ineffective for links that were directly to images.

This commit makes changes to the way ircLinks are processed. The headers are now stored in the database and we can take action on them. In this case, if the header matches 'image', the tumble web renderer will attempt to render it as an image, while still ircLinking to the original item.

The downsides to this could be that NSFW links would now be inlined.

To enable this feature, you also must run a migration on the database.

```
alter table ircLink add column content_type varchar(40);
```

### CODE REVIEW

**Comment by bval** [comment]
I would recommend we implement @rick's NSFW handling from [pages-tumble](https://github.com/websages/pages-tumble) before merging this.

**Comment by stahnma** [comment]
Can I recommend not working someplace that cares about NSFW ;)

I'll check out that bit and see what I can do.

**Comment by stahnma** [comment]
@jameswhite actually env perl would fall back to whatever perl the user choses. In this case, I wanted /usr/bin/perl because of packaging constraints, so env perl would be less accurate.

**Comment by bval** [comment]
@stahnma You can recommend it all day long, and you talk a good game, but I'll bet even at your workplace, you care about NSFW when it comes down to it. ;)

**Comment by stahnma** [comment]
@brandonvalentine I did have an exec pull up kink.com once to show us some cool javascript thing. Those were the days....

**Comment by stahnma** [comment]
Ok, @brandonvalentine implemented behavior to simply fall back to link display only if it detects username nsfw|otd  

I didn't quite have time to complete/play with toggle; but I don't think we need it if this fails safely. (no nsfw content)

**Comment by bval** [comment]
@stahnma :+1:

**Pull request merged**
